target 'AdviceCoach' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

end
